spring.application.name=atendimento
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/atendimento_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.format-sql=true
spring.datasource.initialization-mode=always

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=atendimento
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer